[package]
name = "ace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[build-dependencies]
#pkg-config = "0.3"

[dependencies]
sdl2 = { version = "0.35.2", features = ["bundled", "ttf"] }
